# Generated by Django 3.0.8 on 2020-09-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_image',
            field=models.URLField(null=True),
        ),
    ]
